### ISSUE TITLE
一些小细节处理

### ISSUE THREAD

**Issue by YaoYYoung** [weiguic2w/bubble#2]
- 英文段落中建议使用 ' 和 " 而不是 ’ 和 “”
- 有些三级英文标题使用全大写，个人建议改成小写（？）

---

https://bubble-henna.vercel.app/home/2024-07/5

《Secular Stagnation》那篇文章对应的"And religion addresses"那一段的翻译没有空格。

**Comment by weiguic2w** [comment]
感谢你的建议！多方面原因我放弃了该项目并重新构建了新的外刊网站：https://github.com/wushanglang/ppenglish。这里有更好的文章数据源，更自由的样式布局以提供沉浸阅读。🥰

**Comment by weiguic2w** [comment]
感谢你的建议！多方面原因我放弃了该项目并重新构建了新的外刊网站：https://github.com/wushanglang/ppenglish  。这里有更好的文章数据源，更自由的样式布局以提供沉浸阅读。🥰
